import type { Metadata } from "next"
import { useMessages } from "next-intl"
import { Inter } from "next/font/google"

import "../globals.css"
import NextIntlProvider from "../lib/NextIntlProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Adrien Guesnel - Software Engineer",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = useMessages()

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlProvider
          locale={locale}
          messages={messages}
          timeZone="Europe/Berlin"
          now={new Date()}
        >
          {children}
        </NextIntlProvider>
      </body>
    </html>
  )
}
