import { GoogleTagManager } from "@next/third-parties/google"
import type { Metadata, Viewport } from "next"
import { useMessages } from "next-intl"
import { Inter } from "next/font/google"
import { ToastContainer } from "react-toastify"

import "@/app/globals.css"
import NextIntlProvider from "@/app/lib/NextIntlProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Adrien Guesnel - Software Engineer",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
}

export const viewport: Viewport = {
  themeColor: "#FFF5E1",
  userScalable: false,
  initialScale: 1,
  width: "device-width",
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = useMessages()

  return (
    <html lang={locale}>
      <GoogleTagManager gtmId="GTM-PNCB69TF" />

      <body className={inter.className} suppressHydrationWarning>
        <NextIntlProvider
          locale={locale}
          messages={messages}
          timeZone="Europe/Berlin"
          now={new Date()}
        >
          {children}
          <ToastContainer />
        </NextIntlProvider>
      </body>
    </html>
  )
}
