import { GoogleTagManager } from "@next/third-parties/google";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { getMessages } from "next-intl/server";
import { Toaster } from "sonner";

import "@/src/app/globals.css";

import NextIntlProvider from "@/src/app/lib/NextIntlProvider";

import { ThemeProvider } from "../lib/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adrien Guesnel - Software Engineer",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport: Viewport = {
  themeColor: "#FFF5E1",
  userScalable: false,
  initialScale: 1,
  width: "device-width",
};

type Params = Promise<{ locale: string }>;

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Params;
}) {
  const { locale } = await params;

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <GoogleTagManager gtmId="GTM-PNCB69TF" />

      <body className={inter.className} suppressHydrationWarning>
        <NextIntlProvider
          locale={locale}
          messages={messages}
          timeZone="Europe/Berlin"
          now={new Date()}
        >
          <ThemeProvider>
            {children}
            <Toaster position="top-right" richColors closeButton />
          </ThemeProvider>
        </NextIntlProvider>
      </body>
    </html>
  );
}
