import { GoogleTagManager } from "@next/third-parties/google";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { getMessages } from "next-intl/server";
import { Toaster } from "sonner";

import "@/src/app/globals.css";

import NextIntlProvider from "@/src/app/lib/NextIntlProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adrien Guesnel - Software Engineer",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport: Viewport = {
  themeColor: "#FFF5E1",
  userScalable: false,
  initialScale: 1,
  width: "device-width",
};

type Params = Promise<{ locale: string }>;

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Params;
}) {
  const { locale } = await params;

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <GoogleTagManager gtmId="GTM-PNCB69TF" />

      <body className={inter.className} suppressHydrationWarning>
        <Script id="init-theme" strategy="beforeInteractive">
          {`(function () {
            const stored = localStorage.getItem('data-theme');
            const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
            const theme = stored || (prefersDark ? 'dark' : 'light');
            document.documentElement.dataset.theme = theme;
          })()`}
        </Script>
        <NextIntlProvider
          locale={locale}
          messages={messages}
          timeZone="Europe/Berlin"
          now={new Date()}
        >
          {children}
          <Toaster position="top-right" richColors closeButton />
        </NextIntlProvider>
      </body>
    </html>
  );
}
